#ifndef AHP_COMMANDS_ENUM_H
#define AHP_COMMANDS_ENUM_H

namespace AHP {

enum class AHPCommand {
    HELLO = 0x1,
    ACCEPT = 0x2,
    REJECT = 0x3,
    SET_REALTIME_MODE = 0x4,
    SET_HISTORIAN_MODE = 0x5,
    RESET_MODE = 0x6,
    STOP_REALTIME_SENDING = 0x7,
    GET_REALTIME_VARIABLES = 0x8,
    REALTIME_VARIABLES_RESPONSE = 0x9,
    GET_HISTORIAN_VARIABLES = 0x10,
    GET_HISTORIAN_ALARMS = 0x11,
    HISTORIAN_VARIABLES_RESPONSE = 0x12,
    HISTORIAN_ALARMS_RESPONSE = 0x13,
    DISCONNECT = 0x14,
    MODE_SUCCESSFULL = 0x15
};

}
#endif // AHP_COMMANDS_ENUM_H
